{{- if .Values.modules.vexinationWalker.enabled }}
{{- $reportEnable := .Values.modules.report.enabled }}
{{- range $sourceName, $source := .Values.modules.vexinationWalker.sources }}

{{/* A unique name for the walker */}}
{{- $name := print "vexination-walker-" $sourceName }}

{{/* Override job properties from source */}}
{{- $module := deepCopy $.Values.modules.vexinationWalker }}
{{- if hasKey $source "job" }}
{{ $_ := mergeOverwrite $module $source.job }}
{{- end }}

{{- $mod := dict
  "root" $
  "name" $name
  "component" "vexination"
  "module" $module
-}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $mod.module.stateStorageSize | default "1Mi" | quote }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "trustification.common.name" $mod }}
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
  annotations:
    source: {{ $source.url | quote }}

spec:
  schedule: {{ $mod.module.schedule | default "0 1 * * *" | quote }}
  suspend: {{ $mod.module.suspend | default false }}
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "trustification.common.selectorLabels" $mod | nindent 12 }}

        spec:
          {{- include "trustification.application.pod" $mod | nindent 10 }}

          restartPolicy: OnFailure

          containers:
            - name: walker
              {{- include "trustification.common.defaultImage" $mod | nindent 14 }}

              command: ["/trust"]
              args:
                - "vexination"
                - "walker"
                - "--sink"
                - "{{ include "trustification.tls.http.protocol" $mod }}://vexination-api.{{ $.Release.Namespace }}.svc.cluster.local/api/v1/vex"
                - "--source"
                - {{ $source.url | quote }}
                - "--since-file"
                - "/walker-state/since"
                - "--report-enable"
                - "{{$reportEnable}}"
                {{- if $reportEnable }}
                - "--report-path"
                - "/tmp/share/report"
                {{- end }}
                {{- if eq ( include "trustification.openshift.useServiceCa" $ ) "true" }}
                - --sender-root-certificates
                - /run/secrets/kubernetes.io/serviceaccount/service-ca.crt
                {{- end }}

                {{- if $source.acceptV3Signatures }}
                - "-3"
                {{- end }}

                {{- range $ignore := $source.ignoreDistributions }}
                - "--ignore-distributions"
                - {{ $ignore | quote }}
                {{- end }}

              env:

                {{- if $reportEnable }}
                - name: TEMPLATE_FILE
                  value: "/tmp/report.html"
                {{- end }}
                {{- include "trustification.application.rust.envVars" $mod | nindent 16 }}
                {{- include "trustification.application.infrastructure.envVars" $mod | nindent 16 }}
                {{- include "trustification.oidc.authenticationClient" ( dict "root" $ "clientId" "walker" ) | nindent 16 }}

              ports:
                {{- include "trustification.application.infrastructure.podPorts" $mod | nindent 16 }}

              {{- include "trustification.application.pod" $mod | nindent 14 }}
              {{- include "trustification.application.infrastructure.probes" $mod | nindent 14 }}

              volumeMounts:
                {{- if $reportEnable }}
                - name: report-path
                  mountPath: /tmp/share/report

                - name: template-path
                  mountPath: /tmp/report.html
                  subPath: report.html
                  readOnly: true
                {{- end }}

                - mountPath: /walker-state
                  name: walker-state
                {{- include "trustification.application.extraVolumeMounts" $mod | nindent 16 }}

          volumes:
            {{- if $reportEnable }}
            - name: report-path
              persistentVolumeClaim:
                claimName: report-server
            - name: template-path
              configMap:
                name: report-server-report-template

            {{- end }}

            - name: walker-state
              persistentVolumeClaim:
                claimName: {{ include "trustification.common.name" $mod }}
            {{- include "trustification.application.extraVolumes" $mod | nindent 12 }}

          {{- if $reportEnable }}
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: report
                        operator: In
                        values:
                          - server
                  topologyKey: "kubernetes.io/hostname"
          {{- end }}

{{- end }}{{/* range */}}

{{- end }}
