[serve]
port = 6030

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["dev/trunk-hook.sh"]

#[[proxy]]
# This proxy example has a backend and a rewrite field. Requests received on `rewrite` will be
# proxied to the backend after rewriting the `rewrite` prefix to the `backend`'s URI prefix.
# E.G., `/api/v1/resource/x/y/z` -> `/resource/x/y/z`
#rewrite = "http://localhost:8083/api/v1/cve"
#backend = "http://localhost:8023/cve"

#[[proxy]]
## This proxy example has a backend and a rewrite field. Requests received on `rewrite` will be
## proxied to the backend after rewriting the `rewrite` prefix to the `backend`'s URI prefix.
## E.G., `/api/v1/resource/x/y/z` -> `/resource/x/y/z`
#rewrite = "/api/v1/package"
#backend = "http://localhost:8023/package"

[[hooks]]
stage = "post_build"
command = "bash"
command_arguments = ["mock-server/start-mock-server.sh"]
