version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./container_files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /tmp/share/reports:/tmp/share/reports
    ports:
      - "8018:80"
    expose:
      - "80"