{{- if and .Values.modules.report.enabled .Values.modules.report.enabledAuth}}
{{- $mod := dict "root" . "name" "report-server" "component" "report" "module" .Values.modules.report -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "trustification.common.name" $mod }}-report-auth-secret
  labels:
    app.kubernetes.io/name: report
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
{{- if $mod.module.reportUserConfig.isEncrypt}}
data:
  .htpasswd: {{ $mod.module.reportUserConfig.encryptedHtpasswd}}

{{- else }}
stringData:
  .htpasswd: | {{- range $mod.module.reportUserConfig.users }}
    {{(htpasswd .name .pwd) }}
   {{ end }}
{{ end }}



{{ end }}