{{- if and .Values.modules.report.enabled .Values.modules.report.enabledAuth}}
kind: Secret
apiVersion: v1
metadata:
  name: report-auth-secret
  labels:
    app.kubernetes.io/name: report
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
data:
  .htpasswd: "CmFkbWluOiRhcHIxJFhGQ0ZmenU0JHZ0Zm94MXFlQlBxY1p2ODE0a2x0TDEK"
{{ end }}