{{- if and .Values.modules.report.enabled }}
{{- $mod := dict "root" . "name" "report-server" "component" "report" "module" .Values.modules.report -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trustification.common.name" $mod }}-report-template
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  report.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Walker Report</title>
        <link rel="stylesheet" href="{{ $mod.module.patternflyUrl }}">
        <style>
            .table-section {
                margin-bottom: 20px;
                border-radius: 4px;
                padding: 16px;
                background-color: #ffffff;
            }
            .table-title {
                color: #333;
                font-size: 18px;
                margin-bottom: 10px;
                text-align: center;
            }
        </style>
    </head>
    <body>
    <h1 class="pf-v5-c-title pf-m-4xl">
        {{"{{"}}type{{"}}"}} Walker Report <span class="pf-v5-c-timestamp">
      <time
              class="pf-v5-c-timestamp__text"
              datetime="{{"{{"}}current_time{{"}}"}}"
      >{{"{{"}}current_time{{"}}"}}</time>
    </span>
    </h1>

    <h2>Uploaded <span class="pf-c-badge pf-m-read pf-m-success" >{{"{{"}}report.numer_of_items{{"}}"}}</span> files</h2>


    <div class="pf-c-page">
        <main role="main" class="pf-c-page__main" tabindex="-1">
            <div class="pf-l-stack pf-m-gutter">

                {{"{%"}} for phase, messages in report.messages {{"%}"}}
                <div class="pf-l-stack__item table-section">
                    <h2  class="table-title">Phase: {{"{{"}}phase{{"}}"}}:</h2>
                    <table
                            class="pf-v5-c-table pf-m-grid-md"
                            role="grid"
                            id="table-basic"
                    >
                        <thead class="pf-v5-c-table__thead">
                        <tr class="pf-v5-c-table__tr" role="row">
                            <th class="pf-v5-c-table__th" role="columnheader" scope="col" style="width: 25%;">File</th>
                            <th class="pf-v5-c-table__th" role="columnheader" scope="col" style="width: 15%;">Phase</th>
                            <th class="pf-v5-c-table__th" role="columnheader" scope="col" style="width: 15%;">Severity</th>
                            <th class="pf-v5-c-table__th" role="columnheader" scope="col" style="width: 45%;">Message</th>
                        </tr>
                        </thead>

                        <tbody class="pf-v5-c-table__tbody" role="rowgroup">
                        {{"{%"}} for file, message_list in messages {{"%}"}}
                        {{"{%"}} for msg in message_list {{"%}"}}
                        <tr class="pf-v5-c-table__tr">
                            <td class="pf-v5-c-table__td" role="cell" data-label="File name">{{"{{"}}file{{"}}"}}</td>
                            <td class="pf-v5-c-table__td" role="cell" data-label="Branches">{{"{{"}}phase{{"}}"}}</td>
                            <td class="pf-v5-c-table__td" role="cell" data-label="Pull requests">{{"{{"}}msg.severity{{"}}"}}</td>
                            <td class="pf-v5-c-table__td" role="cell" data-label="Workspaces">{{"{{"}}msg.message{{"}}"}}</td>
                        </tr>
                        {{"{%"}} endfor {{"%}"}}
                        {{"{%"}} endfor {{"%}"}}
                        </tbody>
                    </table>
                </div>
                {{"{%"}} endfor {{"%}"}}
            </div>
        </main>
    </div>

    </body>
    </html>

  metadata.annotations: |
    kubernetes.io/metadata.defaultMode=0755
    {{ end }}