{{- if and .Values.modules.report.enabled .Values.report.auth.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: report-auth-secret
  labels:
    app.kubernetes.io/name: report
    app.kubernetes.io/component: trustification
    app.kubernetes.io/part-of: trustification
data:
  .htpasswd: {{ (htpasswd .Values.report.auth.username .Values.report.auth.password) | b64enc | quote }}

{{ end }}