{{- if and .Values.modules.report.enabled }}
{{- $mod := dict "root" . "name" "report-server" "component" "report" "module" .Values.modules.report -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trustification.common.name" $mod }}-nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    error_log /dev/stdout info;
    server_name  _;
    events {
        worker_connections 1024;
    }
    http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /dev/stdout  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;
      server {
        listen 8018;
        server_name localhost;

        root /opt/app-root/src;
        index index.html index.htm;

        location / {
            autoindex on;
            try_files $uri $uri/ =404;
        }
      }
    }

{{ end }}