{{- if and .Values.modules.report.enabled }}
{{- $mod := dict "root" . "name" "report-server" "component" "report" "module" .Values.modules.report -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trustification.common.name" $mod }}-nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
      server {
        listen 8080;

        root /opt/app-root/src;

        location / {
            {{- if .Values.report.auth.enabled }}
            auth_basic  "Report Area";
            auth_basic_user_file /etc/nginx/.htpasswd;
            {{- end }}
            autoindex on;
        }
      }
    }
{{ end }}