{{- if and .Values.modules.report.enabled }}
{{- $mod := dict "root" . "name" "report-server" "component" "report" "module" .Values.modules.report -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: report-server
  labels:
    {{- include "trustification.common.labels" $mod | nindent 4 }}
  annotations:
{{/*This PVC needs to be created before the other three jobs start, as they will share it.*/}}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $mod.module.stateStorageSize | default "10Gi" | quote }}

{{end}}